
.deploy:
  script:
    - !reference [.create_zip, script]
    # - zipinfo $RELEASE_TAG.zip
    - scp $RELEASE_TAG.env $TARGET_HOST:$TARGET_DIR
    - echo -e "\e[0Ksection_start:`date +%s`:deploy_section_deploy\r\e[0KRunning deploy"
    - scp $RELEASE_TAG.zip $TARGET_HOST:$TARGET_DIR
    - envoy run deploy --sha=$RELEASE_TAG
    - echo -e "\e[0Ksection_end:`date +%s`:deploy_section_deploy\r\e[0K"

.deploy_with_db:
  script:
    - !reference [.create_zip, script]
    - scp $RELEASE_TAG.env $TARGET_HOST:$TARGET_DIR
    - echo -e "\e[0Ksection_start:`date +%s`:deploy_section_deploy_with_db\r\e[0KRunning deploy WITH DB Migrations"
    - envoy run deploy --sha=$RELEASE_TAG --migrate=true
    - echo -e "\e[0Ksection_end:`date +%s`:deploy_section_deploy_with_db\r\e[0K"

.deploy_env:
  cache: []
  script:
    - scp $RELEASE_TAG.env $TARGET_HOST:$TARGET_DIR
    - envoy run deploy_env --sha=$RELEASE_TAG
