
.env_setup_prod:
  script:
    - cat $ENV_PROD > $RELEASE_TAG.env

.deploy_setup_prod:
  stage: deploy
  extends: .prepare_ssh_setup
  variables:
    SSH_KEY_ID: $DEPLOYER_SSH_KEY_ID
    # SSH_CONFIG: $PROD_SSH_CONFIG
    PROJECT_DIR: app.claritytech.io
    RELEASE_TAG: $CI_COMMIT_TAG-$CI_PIPELINE_ID-prod
    TARGET_HOST: your-server-alias
    TARGET_DIR: /home/deployer/$PROJECT_DIR/releases
  resource_group: production
  environment:
    name: production
    deployment_tier: production
    url: https://app.claritytech.io
  when: manual
  only:
    - tags
  tags:
    - clarity
    - deploy
    - production
