
.test_setup:
  stage: test
  coverage: '/^\s*Lines:\s*\d+.\d+\%/'
  dependencies:
    - build backend test
    - build frontend
  needs: ["build backend test", "build frontend"]
  variables:
    REDIS_PORT: 6379
    FF_NETWORK_PER_BUILD: 1
    # FIREBASE_CREDENTIALS: $TEST_FIREBASE_CREDENTIALS
  services:
    - redis:7-alpine
    - mysql:8.0
  before_script:
    - chmod -R 775 storage
    - chmod 775 bootstrap/cache
    - mkdir -p coverage/html
    - chmod -R 775 coverage
  interruptible: true
  except:
    - tags
