
unit tests:
  extends: .test_setup
  script:
    - cp .env.example .env.testing
    #- sed -i -e 's/CACHE_DRIVER=array/CACHE_DRIVER=redis/g' '.env'
    - sed -i -e 's/DB_HOST=127.0.0.1/DB_HOST=mysql/g' '.env.testing'
    - sed -i -e 's/DB_PASSWORD=/DB_PASSWORD=password/g' '.env.testing'
    - cat .env.testing
    - php artisan migrate:refresh --seed --env=testing
    - php artisan optimize:clear --env=testing
    - php artisan key:generate --env=testing
    - ./vendor/phpunit/phpunit/phpunit -d memory_limit=-1 --coverage-text --coverage-cobertura=coverage.cobertura.xml --coverage-html ./coverage/html --colors=never --log-junit rspec-unit.xml
  artifacts:
    paths:
      - ./storage/logs
      - ./coverage
    expire_in: 7 days
    when: always
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.cobertura.xml
      junit: rspec-unit.xml
